### ISSUE TITLE
New android and desktop icon

### ISSUE THREAD

**Issue by hajdam** [exbin/bined#2]
For next release it would be great to have better icon for desktop app as well as icon for planned [android variant](https://github.com/exbin/bined-android/).

Project logo: https://bined.exbin.org/images/logo/bined-logo.png https://bined.exbin.org/images/logo/bined-logo.svg

Currently used but not great desktop icon: https://bined.exbin.org/images/icon-test3.png

Bitmap and/or preferably vector icon for android (and optionally desktop) would be great.

**Comment by Chronomyst** [comment]
Hey, I would like to work on this issue!

**Comment by hajdam** [comment]
Hi,
any contribution would be great.

**Comment by Chronomyst** [comment]
I have made 3 iterations of a design I had in mind. The background is hexadecimal for BinEd. The shape I chose was a hexagon and the internal lines divide the hexagon into the letters H and E standing for BinEd as well. Please review and let me know what you think.

![logo1](https://user-images.githubusercontent.com/35587544/108859482-44766c80-7613-11eb-83a3-644208587845.png)
![logo2](https://user-images.githubusercontent.com/35587544/108859487-45a79980-7613-11eb-8638-afaa2d3cff46.png)
![logo3](https://user-images.githubusercontent.com/35587544/108859489-46403000-7613-11eb-8ac1-370f60defaef.png)

**Comment by hajdam** [comment]
List of icon proposals: https://bined.exbin.org/?icon-proposals

**Comment by hajdam** [comment]
Possible idea I would like could be for example: thick pencil in the front (like a symbol for editing), some "0"s and "1"s in background (as symbol for binary/digital data) like for example two rows like in currently used icon https://bined.exbin.org/images/icon-test3.png but with different font, maybe as lines and hollow rectangles or something...

**Comment by Chronomyst** [comment]
Could you describe more on what you mean by the lines or hollow rectangles
part?

**Comment by Chronomyst** [comment]
How about having the 0/1 format but instead of a simple forward slash
between 0 and 1, it could be the pencil you mentioned

**Comment by hajdam** [comment]
Something like this, but it's just an example. If there is better font or completely different concept, I'm open for suggestions...

https://bined.exbin.org/images/icon/concept1.png

> Could you describe more on what you mean by the lines or hollow rectangles part?

**Comment by Chronomyst** [comment]
What about something like this?

**Comment by hajdam** [comment]
Sorry, I can't say I like that. Well, I don't see any meaning in it neither mathematical nor graphical. But maybe it's me, because with technological background it evokes mathematical division and/or percentage sign, which neither makes sense to me....

**Comment by Chronomyst** [comment]
Okay that's fair, I see what you mean.
I'll think of a few more ideas pertaining to what you want and I'll get
back to you.

**Comment by Chronomyst** [comment]
How do you feel about having a simple square logo with 1/0 centered inside
but instead of the 1 its a pencil

**Comment by Chronomyst** [comment]
That one replaced the slash with the pencil. Since you said it looks too
much like the percentage symbol, I was asking if replacing the 1 instead
would work better

**Comment by hajdam** [comment]
Accepted icon from Reza Almanda.
