### ISSUE TITLE
Support for opening files with drag-and-drop

### ISSUE THREAD

**Issue by Toparvion** [exbin/bined#7]
Currently (as of `v0.2.2 DEV`) the main way to open files in (awesome) BinEd editor is to use standard Open File dialog.
However, it requires some additional actions from the user to navigate to the desired file in this dialog. Being repeated many times and combined with deeply buried files on files system, it may consume a significant amount of time and become an irritating task. This is especially relevant when the user keeps open a file manager open next to BinEd window.

For such cases it would be quite useful to let the user drag a file from a file manager and drop it into BinEd window for opening.
This would significantly increase the application's general usability.

**Comment by hajdam** [comment]
Hi,
thanks for your request.
Added at least basic support for files drag&drop to current development build.
https://bined.exbin.org/editor/

I have this deep in long TODO list along with support for opening new tabs via command line and drag&drop for data insertion and stuff like that - not sure if I'll ever get to it.
Generally, I assume users are not interested in this project anyway, probably better to switch to other projects, like for example
https://imhex.werwolv.net/

**Comment by Toparvion** [comment]
Hi @hajdam,

Thank you very much for your quick response and the desired changing! I've tested it and noticed that BinEd doesn't accept files dragged from Windows 10 Explorer (the cursor shows unsupported action like before the change) but works like a charm when dragging from Double Commander which I use mostly and thus it's totally enough for me. 

As of the tool's popularity, I hope BinEd will stay a favorite in its niche because:
* it is a native citizen for the huge JVM world;
* it has its perfect plugins for IDEs;
* it's a tool that just does its work and does it well without dozens of arguable features.

So thanks again for the work you do!
