### ISSUE TITLE
Force reload and redisplay of file?

### ISSUE THREAD

**Issue by DavidAntliff** [exbin/bined#8]
I'm using `bined` in CLion 2022.3.1.

Perhaps I missed it, but I couldn't find any way to reload an open file from disk, in the event that it has changed. The only method I can find is to close the file completely and then manually re-open it.

Intelli-J supports CTRL+ALT+Y to reload a file, and CLion also supports this, but the displayed contents of a binary file by `bined` is not updated. The old contents remains displayed.

Additionally, if the file could be manually reloaded, it would be nice to have a "follow" mode that automatically updates the file if the contents has changed (but maintains the cursor position, if the file is of sufficient length). This would help when examining parts of files that are being generated repeatedly and often, say by a user's own code during development. If the new file was of a smaller size, then the display could rightfully jump back to the start, or perhaps the end.

**Comment by hajdam** [comment]
Hi,
this is repository for stand-alone desktop version of BinEd. IntelliJ plugin has separate repository https://github.com/exbin/bined-intellij-plugin

I'll try to take a look if it would be possible to add manual reload easily, but there is missing functionality for files locking (multiple modes are supported including partial file opening)...

**Comment by hajdam** [comment]
I added "Reload file" action to popup menu for BinEd intellij plugin development build:
https://bined.exbin.org/download/?bined-intellij-plugin.zip

I still don't know how to intercept reload from disk action as the keyboard shortcut is eaten by IDE. Maybe it could help you a bit at least for now...

**Comment by DavidAntliff** [comment]
@hajdam my apologies, I didn't realise there was a stand-alone version. Thank you for adding the reload file action to the plugin - I will give it a try.

**Comment by DavidAntliff** [comment]
@hajdam I was able to build and install the plugin in CLion, and the "Reload file" action in the right-click menu works well - thank you! This will be very useful.
